-- Create the recipe_details table
CREATE TABLE recipe_details (
                                recipe_id UUID PRIMARY KEY,
                                meal_type VARCHAR(50),
                                description TEXT,
                                food_class VARCHAR(50),
                                region VARCHAR(50),
                                spiciness_level VARCHAR(50),
                                main_ingredients VARCHAR(255),
                                cooking_method VARCHAR(50),
                                FOREIGN KEY (recipe_id) REFERENCES recipes(id)
);

-- Create a temporary table to hold the raw data
CREATE TEMPORARY TABLE temp_recipe_details (
    dish_name VARCHAR(255),
    meal_type VARCHAR(50),
    description TEXT,
    food_class VARCHAR(50),
    region VARCHAR(50),
    spiciness_level VARCHAR(50),
    main_ingredients VARCHAR(255),
    cooking_method VARCHAR(50)
);

-- Insert raw data into the temporary table
INSERT INTO temp_recipe_details (dish_name, meal_type, description, food_class, region, spiciness_level, main_ingredients, cooking_method) VALUES
    ('Abak Atama Soup', 'Dinner', 'A traditional soup from the Ibibio people, made with palm fruit concentrate and Atama leaves.', 'Traditional', 'South-South', 'Mild', 'Palm fruit, Atama leaves, Fish', 'Boiled'),
    ('Achicha Ede (Echicha Ede)', 'Lunch', 'A traditional dish made with cocoyam and vegetables.', 'Traditional', 'Eastern Nigeria', 'Mild', 'Cocoyam, Vegetables, Fish', 'Boiled'),
    ('Afang Soup Nigerian Recipe', 'Dinner', 'A vegetable soup made with Afang leaves and water leaves.', 'Traditional', 'South-South', 'Mild', 'Afang leaves, Water leaves, Meat', 'Boiled'),
    ('Agidi', 'Breakfast', 'Made from corn, it is easy to make and provides a perfect texture.', 'Traditional', 'Nationwide', 'Mild', 'Dry white corn', 'Boiled'),
    ('Akara (Koose, Acaraje)', 'Breakfast', 'Deep-fried bean cakes enjoyed across Nigeria, Ghana, and Brazil.', 'Traditional', 'Nationwide', 'Mild', 'Black-eyed beans, Onions, Peppers', 'Fried'),
    ('Almond Coconut Moi Moi', 'Lunch', 'A variation of moi moi made with almonds and coconut.', 'Contemporary', 'Nationwide', 'Mild', 'Almonds, Coconut, Beans', 'Steamed'),
    ('Asun: Spicy Barbecued Goat Meat', 'Breakfast', 'Spicy grilled goat meat, typically enjoyed as a snack.', 'Traditional', 'South-West', 'High', 'Goat meat, Peppers, Onions', 'Grilled'),
    ('Baked Nigerian Moi Moi', 'Lunch', 'Cup-sized moi moi baked in the oven, loved by kids.', 'Traditional', 'Nationwide', 'Mild', 'Black eyed beans, Peppers', 'Baked'),
    ('Baked Yam and Cheese', 'Lunch', 'Yam baked with cheese and spices.', 'Contemporary', 'Nationwide', 'Mild', 'Yam, Cheese, Spices', 'Baked'),
    ('Banga Rice', 'Lunch', 'Rice cooked with palm fruit concentrate.', 'Traditional', 'South-South', 'Mild', 'Rice, Palm fruit, Fish', 'Boiled'),
    ('Barbecue Chicken Drumsticks', 'Dinner', 'Marinated and baked chicken drumsticks with barbecue sauce.', 'Contemporary', 'Nationwide', 'Mild', 'Chicken drumsticks, Barbecue sauce', 'Baked'),
    ('Beans & Corn (Adalu)', 'Lunch', 'A flavorful mix of beans and corn, seasoned and cooked together.', 'Traditional', 'South-West', 'Mild', 'Beans, Corn', 'Boiled'),
    ('Beef Mince Jollof Rice', 'Lunch', 'Jollof rice cooked with minced beef.', 'Contemporary', 'Nationwide', 'Mild', 'Rice, Minced beef, Tomatoes', 'Boiled'),
    ('Beef and Chicken Stew', 'Dinner', 'A stew made with beef and chicken.', 'Traditional', 'Nationwide', 'Mild', 'Beef, Chicken, Tomatoes', 'Boiled'),
    ('Beer Battered Fish', 'Breakfast', 'Crispy beer battered fish, a twist on fried fish.', 'Contemporary', 'Nationwide', 'Mild', 'Fish, Beer, Flour, Spices', 'Fried'),
    ('Bird Nest Salad', 'Lunch', 'A salad arranged to look like a bird nest.', 'Contemporary', 'Nationwide', 'Mild', 'Lettuce, Carrots, Chicken', 'Raw'),
    ('Bitterleaf Soup (Ofe Onugbu)', 'Dinner', 'Traditional Igbo soup made with bitterleaf.', 'Traditional', 'Eastern Nigeria', 'Mild', 'Bitterleaf, Cocoyam, Meat', 'Boiled'),
    ('Bitterleaf Soup with Cocoyam Powder', 'Dinner', 'A variation of bitterleaf soup made with cocoyam powder.', 'Traditional', 'Eastern Nigeria', 'Mild', 'Bitterleaf, Cocoyam powder, Meat', 'Boiled'),
    ('Boiled White Coconut Rice', 'Lunch', 'White rice cooked with coconut milk.', 'Contemporary', 'Nationwide', 'Mild', 'Rice, Coconut milk', 'Boiled'),
    ('Bread Boat (Baguette Boat)', 'Breakfast', 'A whole new way to enjoy scrambled eggs and bread.', 'Contemporary', 'Nationwide', 'Mild', 'Eggs, Baguette, Sweet peppers, Spinach', 'Baked'),
    ('Breakfast Milky Rice (Milk Rice Pudding)', 'Breakfast', 'A rice pudding made with leftover boiled rice, milk, and sugar.', 'Contemporary', 'Nationwide', 'Mild', 'Boiled rice, Milk, Sugar', 'Boiled'),
    ('Buka Stew(Mama Put Stew)', 'Dinner', 'A rich and flavorful Nigerian stew often served at local eateries.', 'Traditional', 'Nationwide', 'Mild', 'Tomatoes, Meat, Palm oil', 'Boiled'),
    ('Carrot Cupcake', 'Breakfast', 'Moist carrot cupcakes with a delightful aroma.', 'Contemporary', 'Nationwide', 'Mild', 'Carrots, Flour, Sugar, Eggs', 'Baked'),
    ('Catfish Pepper Soup (Point and Kill)', 'Dinner', 'A spicy catfish pepper soup, popular in Nigerian local bars and restaurants.', 'Traditional', 'Nationwide', 'High', 'Catfish, Spices, Peppers', 'Boiled'),
    ('Cauliflower Fried "Rice"', 'Lunch', 'A low-carb alternative to fried rice, made with cauliflower.', 'Contemporary', 'Nationwide', 'Mild', 'Cauliflower, Mixed vegetables, Soy sauce', 'Fried'),
    ('Cauliflower Wrap', 'Lunch', 'A healthy wrap made with cauliflower tortillas.', 'Contemporary', 'Nationwide', 'Mild', 'Cauliflower, Chicken, Vegetables', 'Fried'),
    ('Chicken Pepper Soup', 'Dinner', 'Spicy chicken soup.', 'Traditional', 'Nationwide', 'High', 'Chicken, Ehu (calabash nutmeg), Peppers', 'Boiled'),
    ('Chicken Suya', 'Breakfast', 'Spiced grilled chicken fillets on sticks.', 'Traditional', 'Nationwide', 'High', 'Chicken breast, Suya spice', 'Grilled'),
    ('Chicken Suya Salad', 'Lunch', 'A salad made with grilled suya spiced chicken.', 'Contemporary', 'Nationwide', 'Mild', 'Chicken suya, Lettuce, Tomatoes', 'Mixed'),
    ('Classic Creamy Coleslaw', 'Lunch', 'A creamy coleslaw often served with Jollof rice.', 'Contemporary', 'Nationwide', 'Mild', 'Cabbage, Carrots, Mayonnaise', 'Mixed'),
    ('Classic Nigerian Wedding Cake', 'Breakfast', 'A rich and dense cake, often seen at traditional Nigerian weddings.', 'Traditional', 'Nationwide', 'Mild', 'All-purpose flour, Butter, Sugar, Eggs', 'Baked'),
    ('Club Sandwich', 'Lunch', 'A layered sandwich with chicken, bacon, and vegetables.', 'Contemporary', 'Nationwide', 'Mild', 'Chicken, Bacon, Lettuce, Tomato', 'Assembled'),
    ('Coconut Candy', 'Breakfast', 'A sweet treat made with grated coconut and sugar.', 'Traditional', 'Nationwide', 'Mild', 'Coconut, Sugar', 'Cooked'),
    ('Coconut Curry Sauce', 'Lunch', 'A creamy sauce made with coconut milk and curry spices.', 'Contemporary', 'Nationwide', 'Mild', 'Coconut milk, Curry powder, Chicken', 'Simmered'),
    ('Coconut Flour Pancake', 'Breakfast', 'A delicious pancake made from gluten-free, grain-free coconut flour.', 'Contemporary', 'Nationwide', 'Mild', 'Coconut flour, Eggs, Evaporated milk', 'Fried'),
    ('Coconut Jollof Rice', 'Lunch', 'Jollof rice made with coconut milk for a unique flavor.', 'Contemporary', 'Nationwide', 'Mild', 'Rice, Coconut milk, Tomatoes', 'Boiled'),
    ('Coconut Spaghetti Jollof', 'Lunch', 'A twist on the classic Jollof, using spaghetti and coconut milk.', 'Contemporary', 'Nationwide', 'Mild', 'Spaghetti, Coconut milk, Tomatoes', 'Boiled'),
    ('Cocoyam Fufu', 'Dinner', 'A fufu recipe made from cocoyams.', 'Traditional', 'Nationwide', 'Mild', 'Cocoyam, Cassava flour', 'Boiled'),
    ('Coleslaw', 'Lunch', 'A salad made from finely shredded raw cabbage and dressed most commonly with a vinaigrette.', 'Contemporary', 'Nationwide', 'Mild', 'Cabbage, Carrots, Mayonnaise', 'Mixed'),
    ('Concoction Rice', 'Lunch', 'Traditional rice dish made with minimal ingredients.', 'Traditional', 'Nationwide', 'Mild', 'Rice, Palm oil, Seasoning', 'Boiled'),
    ('Corned Beef Stew (Spaghetti Sauce)', 'Lunch', 'Nigerian red stew made with corned beef instead of chunks of meat.', 'Traditional', 'Nationwide', 'Mild', 'Corned beef, Tomato stew, Spices', 'Boiled'),
    ('Curry Gravy', 'Lunch', 'A flavorful gravy made with curry spices, perfect for rice or potatoes.', 'Contemporary', 'Nationwide', 'Mild', 'Curry powder, Chicken stock, Flour', 'Simmered'),
    ('Delta Starch', 'Lunch', 'Starch commonly served with Banga Soup and Owho Soup.', 'Traditional', 'South-South', 'Mild', 'Cassava tubers, Red palm oil', 'Boiled'),
    ('Easy Fried Rice Recipe', 'Lunch', 'Quick and easy fried rice made with basic ingredients.', 'Contemporary', 'Nationwide', 'Mild', 'Rice, Mixed vegetables, Chicken', 'Fried'),
    ('Edikang Ikong Soup (Vegetable Soup with Ugu and Water Leaves)', 'Dinner', 'A nutritious vegetable soup made with Ugu and Water leaves.', 'Traditional', 'South-South', 'Mild', 'Ugu leaves, Water leaves, Meat', 'Boiled'),
    ('Efo Riro', 'Dinner', 'A rich vegetable soup native to the Yoruba people.', 'Traditional', 'South-West', 'Mild', 'Leafy vegetables, Meat, Spices', 'Boiled'),
    ('Egg Fried Rice', 'Lunch', 'Simple and quick egg fried rice.', 'Contemporary', 'Nationwide', 'Mild', 'Rice, Eggs, Mixed vegetables', 'Fried'),
    ('Egg Whites Omelette', 'Breakfast', 'A healthy omelette made from egg whites and vegetables.', 'Contemporary', 'Nationwide', 'Mild', 'Eggs, Tomatoes, Onions', 'Fried'),
    ('Egusi Soup (Fried Method)', 'Dinner', 'Egusi soup made by frying the ground melon seeds.', 'Traditional', 'Nationwide', 'Mild', 'Egusi, Palm oil, Meat', 'Fried'),
    ('Egusi Soup for Traditional Weddings', 'Dinner', 'Special Egusi soup prepared for weddings.', 'Traditional', 'Nationwide', 'Mild', 'Egusi, Meat, Fish', 'Boiled'),
    ('Egusi Stew for Rice', 'Lunch', 'A stew made with ground melon seeds, often served with rice.', 'Traditional', 'Nationwide', 'Mild', 'Egusi, Tomatoes, Meat', 'Boiled'),
    ('Egusi and Ogbono Soup Combo', 'Dinner', 'A combination of Egusi and Ogbono soups.', 'Traditional', 'Nationwide', 'Mild', 'Egusi, Ogbono, Meat', 'Boiled'),
    ('Ekpang Nkwukwo', 'Lunch', 'A traditional Efik/Ibibio dish made with grated cocoyam and vegetables.', 'Traditional', 'South-South', 'Mild', 'Cocoyam, Vegetables, Meat', 'Steamed'),
    ('Ewa Agoyin', 'Lunch', 'Soft beans served with a spicy pepper sauce.', 'Traditional', 'South-West', 'High', 'Black-eyed beans, Palm oil, Tomatoes, Crayfish', 'Boiled'),
    ('Fried Plantain/Dodo', 'Breakfast', 'Fried slices of ripe plantain.', 'Traditional', 'Nationwide', 'Mild', 'Plantain, Oil', 'Fried'),
    ('Fruit Skewers or Fruit Kebab', 'Breakfast', 'Chunks of fruit on skewers, a refreshing and healthy snack.', 'Contemporary', 'Nationwide', 'Mild', 'Assorted fruits', 'Raw'),
    ('Garden Egg Sauce', 'Dinner', 'A sauce made with garden eggs (African eggplants) and tomatoes.', 'Traditional', 'South-East', 'Mild', 'Garden eggs, Tomatoes, Onions', 'Fried'),
    ('Gbegiri Soup', 'Dinner', 'Bean soup, often served with amala.', 'Traditional', 'South-West', 'Mild', 'Beans, Spices', 'Boiled'),
    ('Goat Meat Pepper Soup', 'Dinner', 'Spicy goat meat soup.', 'Traditional', 'Nationwide', 'High', 'Goat meat, Calabash nutmeg, Peppers', 'Boiled'),
    ('Green Vegetable Garnish', 'Lunch', 'A garnish made from assorted green vegetables.', 'Contemporary', 'Nationwide', 'Mild', 'Green vegetables, Onions', 'Fried'),
    ('Grilled Chicken', 'Dinner', 'A staple in many Nigerian recipes, grilled to perfection.', 'Traditional', 'Nationwide', 'Mild', 'Chicken, Onions, Thyme', 'Grilled'),
    ('Grilled Tilapia (Grilled Fish)', 'Dinner', 'Seasoned and grilled tilapia fish.', 'Traditional', 'Nationwide', 'Mild', 'Tilapia, Garlic, Parsley', 'Grilled'),
    ('Groundnut Soup (Peanut Soup)', 'Dinner', 'A creamy soup made with ground peanuts.', 'Traditional', 'Nationwide', 'Mild', 'Groundnuts, Meat, Vegetables', 'Boiled'),
    ('Isi Ewu: Spicy Goat Head', 'Dinner', 'Spicy goat head dish.', 'Traditional', 'Eastern Nigeria', 'High', 'Goat head, Spices, Palm oil', 'Boiled'),
    ('Iya Dun Dun Fried Yam', 'Lunch', 'Fried yam slices often enjoyed with a spicy sauce.', 'Traditional', 'South-West', 'Mild', 'Yam, Oil', 'Fried'),
    ('Ji Mmanu (Palm Oil Yam)', 'Dinner', 'Boiled yam served with palm oil sauce.', 'Traditional', 'Eastern Nigeria', 'Mild', 'Yam, Palm oil, Onions', 'Boiled'),
    ('Ji Mmiri Oku (Yam Pepper Soup for New Mums)', 'Dinner', 'Yam pepper soup, typically made with goat meat, a postpartum delicacy.', 'Traditional', 'South-East', 'High', 'Yam, Goat meat, Peppers', 'Boiled'),
    ('Jollof Rice Without Tomatoes', 'Lunch', 'A variation of Jollof rice made without tomatoes.', 'Contemporary', 'Nationwide', 'Mild', 'Rice, Spices, Vegetables', 'Boiled'),
    ('Jollof Rice with Mixed Vegetables', 'Lunch', 'Jollof rice cooked with a variety of vegetables.', 'Contemporary', 'Nationwide', 'Mild', 'Rice, Mixed vegetables, Tomatoes', 'Boiled'),
    ('Jollof Rice with Peppered Turkey Wings', 'Lunch', 'Jollof rice served with spicy turkey wings.', 'Contemporary', 'Nationwide', 'High', 'Rice, Turkey wings, Tomatoes', 'Boiled'),
    ('Jollof Stuffed Chicken', 'Lunch', 'Chicken stuffed with Jollof rice.', 'Contemporary', 'Nationwide', 'Mild', 'Chicken, Rice, Tomatoes', 'Baked'),
    ('Keto Bitterleaf Soup (Low Carb Bitterleaf Soup)', 'Dinner', 'A low-carb version of the traditional bitterleaf soup.', 'Contemporary', 'Nationwide', 'Mild', 'Bitterleaf, Meat, Spices', 'Boiled'),
    ('Kilishi (Nigerian Beef Jerky)', 'Breakfast', 'Spicy dried meat similar to beef jerky.', 'Traditional', 'Northern Nigeria', 'High', 'Beef, Spices', 'Dried'),
    ('Leafy Jollof Rice', 'Lunch', 'Jollof rice cooked with green vegetables.', 'Traditional', 'Nationwide', 'Mild', 'Rice, Tomato stew, Green vegetables', 'Boiled'),
    ('Lentils Porridge', 'Lunch', 'A nutritious porridge made from lentils, known for its high fiber content.', 'Contemporary Traditional', 'Nationwide', 'Mild', 'Lentils, Carrots, Onions', 'Boiled'),
    ('Lumpy Nigerian Egusi Soup Recipe', 'Dinner', 'Egusi soup made with lumpy ground melon seeds.', 'Traditional', 'Nationwide', 'Mild', 'Egusi, Palm oil, Meat', 'Boiled'),
    ('Mango Habanero Chicken Wings', 'Breakfast', 'Chicken wings coated in a mango and habanero sauce.', 'Contemporary', 'Nationwide', 'High', 'Chicken, Mango, Habanero pepper', 'Baked'),
    ('Meatball Stew', 'Dinner', 'Stew made with juicy meatballs instead of chunks of meat.', 'Contemporary', 'Nationwide', 'Mild', 'Meatballs, Tomato stew, Spices', 'Boiled'),
    ('Miyan Kuka (Baobab Leaves Soup)', 'Dinner', 'A traditional soup from Northern Nigeria made with dried baobab leaves.', 'Traditional', 'Northern Nigeria', 'Mild', 'Baobab leaves, Meat, Spices', 'Boiled'),
    ('Nigerian Dan Wake', 'Lunch', 'Northern Nigerian dish made from beans flour, known as “son of beans”.', 'Traditional', 'Northern Nigeria', 'Mild', 'Beans flour, Cassava flour, Kuka powder', 'Boiled'),
    ('Nigerian Roasted Yam', 'Lunch', 'Roasted yam slices enjoyed with a spicy sauce.', 'Traditional', 'Nationwide', 'Mild', 'Yam, Oil', 'Roasted'),
    ('Nkwobi: Spicy Cow Foot', 'Dinner', 'Spicy cow foot dish.', 'Traditional', 'Eastern Nigeria', 'High', 'Cow foot, Spices, Palm oil', 'Boiled'),
    ('Ofada Stew (Ayamase)', 'Dinner', 'A spicy stew made with green peppers, commonly served with Ofada rice.', 'Traditional', 'South-West', 'High', 'Green peppers, Assorted meat, Palm oil', 'Fried'),
    ('Ofe Achara with Akpuruakpu Egusi (Mgbam)', 'Dinner', 'Egusi soup with molded egusi balls, a traditional dish.', 'Traditional', 'Eastern Nigeria', 'Mild', 'Egusi, Achara, Stockfish, Spices', 'Boiled'),
    ('Ofe Akwu (Banga Stew)', 'Dinner', 'A rich palm fruit stew popular in Eastern Nigeria.', 'Traditional', 'Eastern Nigeria', 'Mild', 'Palm fruit, Meat, Spices', 'Boiled'),
    ('Ofe Owerri', 'Dinner', 'A rich and hearty traditional soup from Owerri, Imo State.', 'Traditional', 'Eastern Nigeria', 'Mild', 'Assorted meat, Fish, Vegetables', 'Boiled'),
    ('Ofe Ugba (Oil Bean Soup)', 'Dinner', 'A traditional Igbo soup made with oil beans.', 'Traditional', 'Eastern Nigeria', 'Mild', 'Oil beans, Meat, Fish', 'Boiled'),
    ('Ogbono Soup Recipe', 'Dinner', 'A draw soup made with ground ogbono seeds.', 'Traditional', 'Nationwide', 'Mild', 'Ogbono seeds, Meat, Fish', 'Boiled'),
    ('Oha (Ora) Soup', 'Dinner', 'Traditional soup made with Oha leaves.', 'Traditional', 'Eastern Nigeria', 'Mild', 'Oha leaves, Cocoyam, Meat, Spices', 'Boiled'),
    ('Okpa, Okpa di Oku, Okpa Wawa', 'Breakfast', 'A traditional steamed pudding made from Bambara nut flour, popular in the Eastern part of Nigeria.', 'Traditional', 'Eastern Nigeria', 'Mild', 'Bambara nut flour, Palm oil, Peppers', 'Steamed'),
    ('Okra Plantain Porridge', 'Lunch', 'A delicious mix of okra and plantain with smoked fish.', 'Traditional', 'Nationwide', 'Mild', 'Okra, Plantains, Smoked fish', 'Boiled'),
    ('Peeled Beans Porridge', 'Lunch', 'A porridge made from peeled beans, onions, and palm oil, typically enjoyed by families.', 'Traditional', 'Nationwide', 'Mild', 'Beans, Palm oil, Onions, Crayfish', 'Boiled'),
    ('Pepper Rice Stew', 'Lunch', 'A spicy stew made with rice and peppers.', 'Traditional', 'Nationwide', 'High', 'Rice, Peppers, Tomatoes', 'Boiled'),
    ('Pepper Stew (Obe Ata Din Din)', 'Lunch', 'A rich and spicy pepper stew.', 'Traditional', 'Nationwide', 'High', 'Peppers, Tomatoes, Onions', 'Fried'),
    ('Peppered Fish', 'Lunch', 'Fried fish served with a spicy pepper sauce.', 'Traditional', 'Nationwide', 'High', 'Fish, Peppers, Spices', 'Fried'),
    ('Peppered Gizzards Recipe', 'Breakfast', 'Fried gizzards coated in a spicy sauce.', 'Traditional', 'Nationwide', 'High', 'Gizzards, Peppers, Onions', 'Fried'),
    ('Peppered Puff Puff', 'Breakfast', 'A spicy variation of the traditional puff puff.', 'Contemporary', 'Nationwide', 'Mild', 'Flour, Peppers, Sugar', 'Fried'),
    ('Peppered Snails', 'Breakfast', 'Spicy snails enjoyed as a delicacy.', 'Traditional', 'Nationwide', 'High', 'Snails, Peppers, Spices', 'Fried'),
    ('Perfect Nigerian Pancakes', 'Breakfast', 'Nigerian Pancakes are moist, supple, and delicious.', 'Traditional', 'Nationwide', 'Mild', 'All-purpose flour, Eggs, Evaporated milk, Sugar', 'Fried'),
    ('Plantain Bread', 'Breakfast', 'Bread made with ripe plantains.', 'Contemporary', 'Nationwide', 'Mild', 'Plantains, Flour, Sugar', 'Baked'),
    ('Plantain Fufu', 'Dinner', 'Fufu made from unripe plantains.', 'Traditional', 'Nationwide', 'Mild', 'Unripe plantains', 'Boiled'),
    ('Plantain Moi Moi (Ukpo Ogede)', 'Lunch', 'A plantain-based moi moi, typically served as a snack or side.', 'Traditional', 'Eastern Nigeria', 'Mild', 'Overripe plantains, Plantain flour, Palm oil', 'Steamed'),
    ('Plantain Mosa (Plan-Cakes)', 'Breakfast', 'Pancakes made with plantains.', 'Contemporary', 'Nationwide', 'Mild', 'Plantains, Flour, Sugar', 'Fried'),
    ('Plantain Mosa (Plantain Puffs)', 'Breakfast', 'Small fried snacks made from mashed plantains.', 'Contemporary', 'Nationwide', 'Mild', 'Plantains, Flour, Sugar', 'Fried'),
    ('Plantain Omelette', 'Breakfast', 'Omelette made with slices of plantains.', 'Contemporary', 'Nationwide', 'Mild', 'Plantains, Eggs, Onions', 'Fried'),
    ('Plantain Pies (Over-ripe Plantain Recipe)', 'Breakfast', 'A tasty pie made from over-ripe plantains.', 'Contemporary', 'Nationwide', 'Mild', 'Over-ripe plantains, Flour', 'Baked'),
    ('Potato Fufu', 'Dinner', 'Fufu made from potatoes and oats.', 'Contemporary', 'Nationwide', 'Mild', 'Irish potatoes, Oats', 'Boiled'),
    ('Potato Love Island (Mashed Potato with Sauce)', 'Lunch', 'Mashed potatoes served with a savory sauce.', 'Contemporary', 'Nationwide', 'Mild', 'Potatoes, Butter, Milk', 'Boiled'),
    ('Potato Mash Recipe', 'Lunch', 'Classic mashed potatoes.', 'Contemporary', 'Nationwide', 'Mild', 'Potatoes, Butter, Milk', 'Boiled'),
    ('Potato Omelette (Potato Fritata)', 'Breakfast', 'Inspired by the Spanish Tortilla de Patatas.', 'Contemporary', 'Nationwide', 'Mild', 'Irish potatoes, Eggs, Sweet peppers', 'Fried'),
    ('Potato Pepper Soup', 'Lunch', 'A pepper soup made with potatoes.', 'Contemporary', 'Nationwide', 'High', 'Potatoes, Peppers, Meat', 'Boiled'),
    ('Potato Pottage/Porridge', 'Lunch', 'A hearty potato dish cooked in a flavorful sauce.', 'Contemporary', 'Nationwide', 'Mild', 'Potatoes, Tomatoes, Meat', 'Boiled'),
    ('Potato Stir-fry', 'Lunch', 'Stir-fried potatoes with chicken and vegetables.', 'Contemporary', 'Nationwide', 'Mild', 'Potatoes, Chicken, Vegetables', 'Fried'),
    ('Potato and Fish Porridge', 'Lunch', 'A nourishing porridge made with potatoes and fish.', 'Contemporary', 'Nationwide', 'Mild', 'Potatoes, Fish, Vegetables', 'Boiled'),
    ('Pounded Yam', 'Dinner', 'A popular Nigerian fufu made from white puna yam.', 'Traditional', 'Nationwide', 'Mild', 'White puna yam', 'Pounded'),
    ('Rice Salad', 'Lunch', 'A salad made with cooked rice and vegetables.', 'Contemporary', 'Nationwide', 'Mild', 'Rice, Vegetables, Dressing', 'Mixed'),
    ('Rice and Beans', 'Lunch', 'A mix of rice and beans, cooked together.', 'Traditional', 'Nationwide', 'Mild', 'Rice, Beans, Tomato stew', 'Boiled'),
    ('Rivers Native Soup', 'Dinner', 'A rich soup from the Rivers State, made with seafood and vegetables.', 'Traditional', 'South-South', 'Mild', 'Seafood, Vegetables, Spices', 'Boiled'),
    ('Roasted Plantain (Boli)', 'Breakfast', 'Roasted plantain, often enjoyed with groundnut.', 'Traditional', 'Nationwide', 'Mild', 'Plantain', 'Roasted'),
    ('Seafood Okra Soup', 'Dinner', 'Okra soup with assorted seafood.', 'Traditional', 'Nationwide', 'Mild', 'Okra, Fish, Shrimp, Palm oil', 'Boiled'),
    ('Sinasir (Rice Pancakes)', 'Breakfast', 'Rice pancakes, often served with soup or honey.', 'Traditional', 'Northern Nigeria', 'Mild', 'Rice, Sugar, Yeast', 'Fried'),
    ('Smoked Fish', 'Dinner', 'Traditional smoked fish used in various Nigerian dishes.', 'Traditional', 'Nationwide', 'Mild', 'Mackerel fish', 'Smoked'),
    ('Smoky Party Jollof Rice', 'Lunch', 'A version of Jollof rice with a smoky flavor, often served at parties.', 'Traditional', 'Nationwide', 'Mild', 'Rice, Tomatoes, Spices', 'Boiled'),
    ('Suya Recipe', 'Breakfast', 'Spicy skewered meat, a popular street food in Nigeria.', 'Traditional', 'Nationwide', 'High', 'Beef, Suya spice, Onions', 'Grilled'),
    ('Tomato Omelette', 'Breakfast', 'A delicious morning recipe made with eggs and tomatoes.', 'Traditional', 'Nationwide', 'Mild', 'Eggs, Tomatoes, Onions', 'Fried'),
    ('Tomato Stew', 'Lunch', 'A versatile tomato-based stew, used in various Nigerian dishes.', 'Traditional', 'Nationwide', 'Mild', 'Tomatoes, Onions, Spices', 'Boiled'),
    ('Turmeric Rice(Yellow Rice)', 'Lunch', 'Rice cooked with turmeric, giving it a vibrant yellow color.', 'Contemporary', 'Nationwide', 'Mild', 'Rice, Turmeric, Spices', 'Boiled'),
    ('Unripe Plantain Porridge', 'Lunch', 'A nutritious porridge made with unripe plantains.', 'Traditional', 'Nationwide', 'Mild', 'Unripe plantains, Palm oil, Spices', 'Boiled'),
    ('Urhobo Owho Soup', 'Dinner', 'A rich soup from the Urhobo people, made with starch and palm oil.', 'Traditional', 'South-South', 'Mild', 'Starch, Palm oil, Meat', 'Boiled'),
    ('Vegetable Couscous Recipe', 'Lunch', 'Couscous with a variety of vegetables and chicken.', 'Contemporary', 'Nationwide', 'Mild', 'Couscous, Chicken, Mixed vegetables', 'Boiled'),
    ('Vegetable and Shrimp Sauce', 'Lunch', 'Sauce made with vegetables and shrimp, perfect for boiled staples.', 'Contemporary', 'Nationwide', 'Mild', 'Shrimp, Vegetables, Spices', 'Boiled'),
    ('White Moi Moi (Ekuru)', 'Lunch', 'White version of moi moi, a bean-based dish without the addition of palm oil.', 'Traditional', 'South-West', 'Mild', 'Black eyed beans, Onions', 'Steamed'),
    ('White Rice', 'Lunch', 'Plain white rice, a staple in Nigerian cuisine.', 'Traditional', 'Nationwide', 'Mild', 'Rice', 'Boiled'),
    ('Yam Balls (Ji Akpurakpu)', 'Breakfast', 'Fried balls made from mashed yam.', 'Traditional', 'Eastern Nigeria', 'Mild', 'Yam, Spices, Onions', 'Fried'),
    ('Yam Porridge', 'Lunch', 'A hearty porridge made with yam and vegetables.', 'Traditional', 'Nationwide', 'Mild', 'Yam, Vegetables, Palm oil', 'Boiled'),
    ('Yam Porridge with Bitterleaf', 'Lunch', 'Traditional yam porridge with bitterleaf.', 'Traditional', 'Eastern Nigeria', 'Mild', 'Yam, Bitterleaf, Palm oil, Spices', 'Boiled'),
    ('Yam and Vegetable Sauce (Ji Abubo)', 'Lunch', 'Yam served with a vegetable sauce.', 'Traditional', 'Nationwide', 'Mild', 'Yam, Vegetables, Palm oil', 'Boiled'),
    ('Assorted Meat Pepper Soup', 'Dinner', 'A spicy soup made with assorted meats.', 'Traditional', 'Nationwide', 'High', 'Assorted meats, Spices, Peppers', 'Boiled'),
    ('Bake a Cake Without an Oven', 'Dessert', 'A method for baking a cake without using an oven.', 'Contemporary', 'Nationwide', 'Mild', 'Flour, Sugar, Eggs, Butter', 'Steamed');



-- Insert data from the temporary table into the recipe_details table
INSERT INTO recipe_details (recipe_id, meal_type, description, food_class, region, spiciness_level, main_ingredients, cooking_method)
SELECT r.id, t.meal_type, t.description, t.food_class, t.region, t.spiciness_level, t.main_ingredients, t.cooking_method
FROM temp_recipe_details t
         JOIN recipes r ON t.dish_name = r.name;

-- Drop the temporary table
DROP TABLE temp_recipe_details;
